# Generated by Django 4.0.4 on 2022-05-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgUserId', models.IntegerField()),
                ('cashBack', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('inVoiceId', models.IntegerField()),
                ('price', models.IntegerField(blank=True, null=True)),
                ('cashBackDate', models.DateField(auto_now=True)),
                ('inVoiceDate', models.DateField()),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
    ]
