# Generated by Django 4.0.4 on 2022-05-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='inVoiceDate',
        ),
    ]
