# Generated by Django 4.0.4 on 2022-05-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_userinfo_invoicedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='inVoiceId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
