# Generated by Django 4.0.4 on 2022-05-26 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_userinfo_invoiceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='tgUserId',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceId', models.CharField(max_length=20, unique=True)),
                ('cashBack', models.IntegerField(blank=True, null=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.userinfo')),
            ],
        ),
    ]
