# Generated by Django 4.0.4 on 2022-05-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_userinfo_tguserid_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='cashBack',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='UserId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
